name: Publish Coverage

on:
  push:
    branches:
      - master
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm install
      - run: sudo apt update -y && sudo apt install ffmpeg fonts-liberation -y
      - run: npm test
      - name: Execute tests
        run: npm run test -- --coverage
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
